name: binance_spot
description: Unofficial Dart wrapper for Binance SPOT API (REST endpoints + Websockets).
version: 0.0.3
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  convert: ^3.0.1
  crypto: ^3.0.1
  either_dart: ^0.1.3
  http: ^0.13.4
  web_socket_channel: ^2.1.0
